### PR TITLE
Disable Marpit polyfill when using VS Code >= 1.36 (Electron 4)

### LINKED ISSUE #45: Link has wrong hit area in VS Code 1.36-insider
The latest build of VS Code 1.36-insider has updated Electron from 3.x to 4.x.

```
Version: 1.36.0-insider
Commit: c089daa858f34631f5f827ff8a0313bf1e2ded6d
Date: 2019-06-07T06:13:41.194Z
Electron: 4.2.3
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0
```

I have already known Chrome <= 69 still has a serious bug in rendering Marpit's inline SVG slide. (See marp-team/marpit#35 that I found a year ago)

Chrome 66 (Electron 3.x) cannot scale hit area and rendering by inline SVG. Only DevTool knows the actual scaled DOM. I had same issue in https://github.com/marp-team/marp-cli/pull/15. Fortunately we can fix it by just applying a WebKit polyfill manually, so Marp for VS Code had used [marpit-svg-polyfill](https://github.com/marp-team/marpit-svg-polyfill).

In Chrome 69 (Electron 4.x), only the hit area is following correct scaling by inline SVG, and rendering is not. The polyfill should keep using to fix rendering, but hit area will too scaled.

electron4

### PR DESCRIPTION
**Pull request by yhatt**
I've found just disabled [@marp-team/marpit-svg-polyfill](https://github.com/marp-team/marpit-svg-polyfill) can fix the strange hit area reported at #45. This PR will detect the version of VS Code and toggle whether to apply polyfill.

Resolves #45.

> ℹ️ We have already known edge cases to bring glitch to rendering CSS 3D transform and `<video>` element in Electron 4 without polyfill, so I added the comment about rendering in Electron 3-6.

### CODE REVIEW

File: src/option.ts [hunk 1]
```diff
@@ -1,10 +1,21 @@
...
 
+// WebKit polyfill requires in VS Code < 1.36 (Electron 3).
+//
+// NOTE: Electron 3 has got a stable rendering by applying WebKit polyfill. And
+// Electron 4 has almost stable rendering even if polyfill is not used but still
+// remains glitch when used CSS 3D transform and video component. Electron 5
+// also has a glitch in video, and we have to wait for stable rendering until
+// Electron 6.
+const coercedVer = coerce(version)
+const isRequiredPolyfill = coercedVer ? lt(coercedVer, '1.36.0') : false
```
Comment (yhatt) [inline src/option.ts]: VS Code seems not to provide API for getting Electron version. Instead we are using known VS Code version.
